# Generated by Django 4.0.4 on 2022-05-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('titulo', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('titulo', models.CharField(max_length=320)),
                ('passo_a_passo', models.CharField(blank=True, max_length=320, null=True)),
                ('topicos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.topicos')),
            ],
        ),
    ]
