# Generated by Django 4.0.4 on 2022-05-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='titulo',
        ),
    ]
