# Generated by Django 4.0.4 on 2022-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_procedimento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='falha',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='sucesso',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='passo_a_passo',
            field=models.CharField(default='', max_length=320),
            preserve_default=False,
        ),
    ]
