# Generated by Django 4.0.4 on 2022-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_procedimento_falha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='relacionados',
            field=models.ManyToManyField(to='helpdesk.procedimento'),
        ),
    ]
